services:
  foodies-postgres:
    container_name: foodies-postgres
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 1s
    env_file:
      - .env
    volumes:
      - ./volumes/postgres-db:/var/lib/postgresql/data

  foodies-api:
    container_name: foodies-api
    restart: always
    networks:
      - shared_nginx_web_network
    depends_on:
      foodies-postgres:
        condition: service_healthy
    ports:
      - 9000:9000
    env_file:
      - .env
    build:
      context: .
      dockerfile: prod.Dockerfile

networks:
  shared_nginx_web_network:
    external: true
